### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by divane1** [smalek00/t430-mojave-efi#1]
onymous UUID:       5AEA2EF4-3D2B-54F5-B0C6-B8186109C75D

Mon Nov 19 14:47:56 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff8022ed84dd): Kernel trap at 0xffffff80234067a0, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff802397e98f, CR3: 0x000000002b1a2000, CR4: 0x00000000001626e0
RAX: 0x0000000000000000, RBX: 0x0000000000000833, RCX: 0x0000000000000000, RDX: 0x0000000000016050
RSP: 0xffffff8196a7bad0, RBP: 0xffffff8196a7bad0, RSI: 0xffffff80239896d8, RDI: 0xffffff802397e98f
R8:  0xffffff80400ca7e8, R9:  0x000000000000b9dc, R10: 0x0000000000000001, R11: 0x0000000000000000
R12: 0x0000000000000eae, R13: 0x0000000000000eae, R14: 0xffffff80400ca770, R15: 0xffffff8196325960
RFL: 0x0000000000010246, RIP: 0xffffff80234067a0, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff802397e98f, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 2

Backtrace (CPU 2), Frame : Return Address
0xffffff8196a7b5a0 : 0xffffff8022daca9d 
0xffffff8196a7b5f0 : 0xffffff8022ee6893 
0xffffff8196a7b630 : 0xffffff8022ed82ba 
0xffffff8196a7b6a0 : 0xffffff8022d59ca0 
0xffffff8196a7b6c0 : 0xffffff8022dac4b7 
0xffffff8196a7b7e0 : 0xffffff8022dac303 
0xffffff8196a7b850 : 0xffffff8022ed84dd 
0xffffff8196a7b9c0 : 0xffffff8022d59ca0 
0xffffff8196a7b9e0 : 0xffffff80234067a0 
0xffffff8196a7bad0 : 0xffffff802340661b 
0xffffff8196a7bb50 : 0xffffff8023406b47 
0xffffff8196a7bbc0 : 0xffffff8023404bd5 
0xffffff8196a7bc50 : 0xffffff8023405579 
0xffffff8196a7bcc0 : 0xffffff80233d2be1 
0xffffff8196a7bda0 : 0xffffff80233d0aac 
0xffffff8196a7be10 : 0xffffff80233de658 
0xffffff8196a7be60 : 0xffffff802344dc0b 
0xffffff8196a7be80 : 0xffffff802342b8e1 
0xffffff8196a7bf00 : 0xffffff802342b4c7 
0xffffff8196a7bf50 : 0xffffff802342cf96 
0xffffff8196a7bfa0 : 0xffffff8022d590ce 

BSD process name corresponding to current thread: Unknown
Boot args: dart=0 darkwake=0 kext-dev-mode=1  -rootdmg-ramdisk auth-root-dmg=file:///macOS%20Install%20Data/BaseSystem.dmg

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Kernel UUID: 5D53F7E4-472A-369D-97D8-4DD877A4BDFF
Kernel slide:     0x0000000022a00000
Kernel text base: 0xffffff8022c00000
__HIB  text base: 0xffffff8022b00000
System model name: MacBookPro9,2 (Mac-6F01561E16C75D06)

System uptime in nanoseconds: 2828237847
last loaded kext at 2802201845: com.apple.driver.usb.AppleUSBEHCIPCI	1.2 (addr 0xffffff7fa388e000, size 65536)
loaded kexts:
com.insanelymac.IntelMausiEthernet	2.3.0
org.hwsensors.driver.ACPISensors	1800
org.rehabman.driver.AppleSmartBatteryManager	1.90.1
org.rehabman.voodoo.driver.PS2Controller	1.9.2
org.hwsensors.driver.CPUSensors	1800
as.vit9696.AppleALC	1.3.2
org.netkas.driver.FakeSMC	1800
as.lvs1974.HibernationFixup	1.2.3
com.rehabman.driver.USBInjectAll	0.6.9
as.vit9696.WhateverGreen	1.2.3
as.vit9696.Lilu	1.2.7
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.private.KextAudit	1.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.0.0
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	220.0.0
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.200.8
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.200.1
com.apple.iokit.IOSCSIArchitectureModelFamily	408.200.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.iokit.IOTimeSyncFamily	700.7
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOBluetoothFamily	6.0.9f2
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.iokit.IOReportFamily	47
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro9,2, BootROM MBP91.00DA.B00, 2 processors, Intel Core i5, 2.59 GHz, 12 GB, SMC 2.2f44
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, SK Hynix, HMT41GS6AFR8A-PBN0
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1600 MHz, SK Hynix, HMT451S6AFR8C-PBN0
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: LITEONIT LCT-128M3S 2.5 7mm 128GB, 128.04 GB
Serial ATA Device: Optiarc DVD ROM DDU7740H
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Integrated Camera
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 3.0 Bus
Thunderbolt Bus:

**Comment by smalek00** [comment]
try starting with -v, I can only boot if I have verbose mode enabled :/

**Comment by smalek00** [comment]
Also note I changed InjectKexts to Detect in config.plist.
